var canvDiv,flow,nodes=[],curTime=0,fps=60,sps=120,dragging=null,mouse=[0,0],wiring,play=true,examples=[{name:"plot sines",scn:{nodes:[{type:"Logger",x:500,y:200},{type:"Summer",x:200,y:100},{type:"Mouse",x:100,y:180},{type:"Time",x:50,y:410},{type:"Sine",x:50,y:300,i:{freq:0.5}},{type:"Sine",x:200,y:300,i:{freq:4.05}},{type:"Scope",x:500,y:350},{type:"Custom",x:200,y:400},{type:"X2",x:350,y:150}],wires:[{n1:4,p1:"y",n2:5,p2:"amp",color:100},{n1:5,p1:"y",n2:6,p2:"y1",color:220},{n1:1,p1:"c",n2:8,
p2:"a",color:0},{n1:8,p1:"b",n2:0,p2:"msg",color:100},{n1:3,p1:"t",n2:7,p2:"a",color:320},{n1:3,p1:"t",n2:6,p2:"x",color:320},{n1:7,p1:"x",n2:6,p2:"y2",color:0},{n1:7,p1:"y",n2:6,p2:"y3",color:100}]}},{name:"SR latch",scn:{nodes:[{type:"button",title:"",x:218,y:178,i:{}},{type:"button",title:"",x:216,y:260,i:{}},{type:"NOR",title:"NOR",x:384,y:179,i:{a:false,b:false}},{type:"NOR",title:"NOR",x:384,y:259,i:{a:true,b:false}}],wires:[{n1:"0",p1:"o",n2:"2",p2:"a",color:"hsl(200, 50%, 55%)"},{n1:"3",p1:"y",
n2:"2",p2:"b",color:"hsl(200, 50%, 55%)"},{n1:"1",p1:"o",n2:"3",p2:"b",color:"hsl(200, 50%, 55%)"},{n1:"2",p1:"y",n2:"3",p2:"a",color:"hsl(200, 50%, 55%)"}]}}];function init(){canvDiv=document.getElementById("container");makeTypes();step();(function b(){requestAnimFrame(b);draw()})();makeLibrary()}
var draw=function(){if(play)for(var a in nodes)nodes[a].draw()},step=function step(){if(play){curTime+=1/sps;for(var b in nodes)nodes[b].eval();for(b in nodes)nodes[b].progress()}window.setTimeout(step,1E3/sps)};Math.dist=function(a,b,c,d){return Math.sqrt((a-c)*(a-c)+(b-d)*(b-d))};objectSize=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();var Node=function(a,b){this.inputs={};this.outputs={};var c={},d={};this.type=a.type;this.vars={};for(var e in a.i)c[e]=a.i[e];for(e in a.o)d[e]=a.o[e];for(e in b.i)c[e]=b.i[e];for(e in b.o)d[e]=b.o[e];var f=a.init||null,g=a.step||null,h=a.f||function(){};if(a.vars)for(e in a.vars)this.vars[e]=a.vars[e];if(b.vars)for(e in b.vars)this.vars[e]=b.vars[e];for(e in c)this.inputs[e]={src:{val:c[e],flag:-1}};for(e in d)this.outputs[e]={node:this,val:d[e],flag:false};this.newCode=function(a){h=new Function("i",
"o","that",a)};e=new Widget(this);e.title=b.title||a.title||"";e.resize();b.x&&b.y&&e.upLoc(b.x,b.y);this.widget=e;var i=true;f&&f(c,d,this);this.doExport=function(){var a={};a.type=this.type;a.title=this.widget.title;a.x=this.widget.x;a.y=this.widget.y;a.i={};for(var b in this.inputs)a.i[b]=this.inputs[b].src.val;for(b in this.vars){if(!a.vars)a.vars={};a.vars[b]=this.vars[b]}return a};this.draw=function(){i&&(a.draw&&a.draw(c,d,this),this.widget.upLabels(),i=false)};this.eval=function(){var a=false,
b;for(b in c)if(this.inputs[b].src.flag){a=true;c[b]=this.inputs[b].src.val;if(this.inputs[b].src.flag==-1)this.inputs[b].src.flag=false;i=true}a&&h(c,d,this);g&&(g(c,d,this),i=true)};this.progress=function(){for(var a in d)if(this.outputs[a].flag=false,d[a]!=this.outputs[a].val)this.outputs[a].val=d[a],i=this.outputs[a].flag=true};this.remove=function(){a.remove&&a.remove(c,d,this);for(var b in this.widget.inWires)rmWire(this,b);for(var e in nodes){b=nodes[e];for(var f in b.inputs)b.inputs[f].src.node&&
b.inputs[f].src.node==this&&rmWire(b,f)}nodes.splice(nodes.indexOf(this),1);this.widget.remove()};this.widget.upLoc();this.widget.redraw();nodes.push(this)};var selectStart,selectBox,selected=[];function makeLibrary(){var a="Examples:<ul>",b;for(b in examples)a+='<li><a href="#" onclick="loadScene(examples['+b+'].scn);return false;">'+examples[b].name+"</a></li>";a+="</ul>";a+="Add:<ul>";for(b in nodeTypes)a+='<li><a href="#" onmousedown="dragging=[makeNode({type:\''+b+"',x:event.clientX-30,y:event.clientY-10})];return false;\">"+b+"</a></li>";a+="</ul>";document.getElementById("library").innerHTML=a}
function togglePlay(){play=!play;document.getElementById("playPause").innerHTML=play?"pause":"play"}function saveLocal(){localStorage.setItem("scene",JSON.stringify(exportNodes(nodes)))}function openLocal(){loadScene(JSON.parse(localStorage.getItem("scene")))}function loadScene(a){deleteNodes(nodes);importNodes(a);curTime=0}
document.onkeydown=function(a){if(a.target.type!="textarea"&&a.target.type!="text")switch(a.which){case 8:case 46:a.preventDefault();deleteNodes(selected);break;case 32:a.preventDefault();togglePlay();break;case 68:duplicate();break;case 67:copyNodes(selected);break;case 86:pasteNodes();break;case 88:cutNodes(selected);break;case 79:openLocal();break;case 83:saveLocal()}};
document.onmousedown=function(a){mouse=getMouse(a);if(a.target.id=="container"||a.target.nodeName=="HTML"){if(!selectBox)selectBox=document.createElement("div"),canvDiv.appendChild(selectBox),selectBox.className="selectBox";selectStart=getMouse(a);doSelectBox()}};function select(a){selected.push(a);a.widget.redraw()}function deselect(a){if(a)selected.splice(selected.indexOf(a),1),a.widget.redraw();else for(a=selected.length-1;a>=0;a--)deselect(selected[a])}
document.onmouseup=function(a){mouse=getMouse(a);dragging=null;wiring&&(wiring[2].remove(),wiring=null);if(selectStart)doSelectBox(),selectStart=false,selectBox.style.visibility="hidden"};
document.onmousemove=function(a){newMouse=getMouse(a);if(dragging){var a=newMouse[0]-mouse[0],b=newMouse[1]-mouse[1],c;for(c in dragging)dragging[c].widget.x+=a,dragging[c].widget.y+=b,dragging[c].widget.upLoc()}wiring&&(wiring[3][0]=newMouse[0],wiring[3][1]=newMouse[1],wiring[2].redraw());if(selectStart)selectBox.style.width=Math.abs(newMouse[0]-selectStart[0])+"px",selectBox.style.height=Math.abs(newMouse[1]-selectStart[1])+"px",selectBox.style.left=Math.min(newMouse[0],selectStart[0])+"px",selectBox.style.top=
Math.min(newMouse[1],selectStart[1])+"px",selectBox.style.visibility="visible",doSelectBox();mouse=newMouse};document.onblur=function(){dragging=null;if(selectStart)selectStart=false,selectBox.style.visibility="hidden"};
function doSelectBox(){var a=Math.min(mouse[0],selectStart[0]),b=Math.max(mouse[0],selectStart[0]),c=Math.min(mouse[1],selectStart[1]),d=Math.max(mouse[1],selectStart[1]),e;for(e in nodes){var f=nodes[e],g=f.widget;(g=g.x<b&&g.x+g.w>a&&g.y<d&&g.y+g.h>c)&&selected.indexOf(f)==-1?select(f):!g&&selected.indexOf(f)!=-1&&deselect(f)}}function deleteNodes(a){for(var b=a.length-1;b>=0;b--){var c=a[b];deselect(c);c.remove()}}function cutNodes(a){copyNodes(a);deleteNodes(a)}
function copyNodes(a){var a=exportNodes(a),b;for(b in a.nodes)a.nodes[b].x-=mouse[0],a.nodes[b].y-=mouse[1];localStorage.setItem("pasteboard",JSON.stringify(a))}function pasteNodes(){var a=JSON.parse(localStorage.getItem("pasteboard")),b;for(b in a.nodes)a.nodes[b].x+=mouse[0],a.nodes[b].y+=mouse[1];a=importNodes(a);deselect();for(b in a)select(a[b])}
function exportNodes(a){var b=[],c=[],d;for(d in a){var e=a[d];b.push(e.doExport());for(var f in e.widget.inWires){var g=e.widget.inWires[f],h;for(h in a){var i=a[h],j;for(j in i.widget.outWires)for(var m in i.widget.outWires[j])g==i.widget.outWires[j][m]&&c.push({n1:h,p1:j,n2:d,p2:f,color:g.color})}}}return{nodes:b,wires:c}}function importNodes(a){var b=[],c;for(c in a.nodes)b[c]=makeNode(a.nodes[c]);for(var d in a.wires)c=a.wires[d],mkWire(b[c.n1],c.p1,b[c.n2],c.p2,c.color);return b}
function makeNode(a){return new nodeTypes[a.type](a)}function duplicate(){var a=exportNodes(selected);deselect();var a=importNodes(a),b;for(b in a)select(a[b]);dragging=selected}function getMouse(a){var b=0,c=0;if(!a)a=window.event;if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return[b,c]};var Widget=function(a){this.title="";this.x=20;this.y=40;this.w=120;this.h=80;var b=document.createElement("div");canvDiv.appendChild(b);b.className="node";var c=document.createElement("canvas");b.appendChild(c);var d;c.style["pointer-events"]="none";var e=false;this.box=document.createElement("div");b.appendChild(this.box);this.box.className="nodeBox";this.box.style.position="absolute";this.box.style.top="20px";this.box.style.left="10px";this.inWires={};this.outWires={};var f={},g={};this.makeLabels=
function(){for(var d in a.inputs){var c=document.createElement("div");c.className="iLabel";b.appendChild(c);c.innerHTML=d;f[d]=c}for(d in a.outputs)c=document.createElement("div"),c.className="oLabel",b.appendChild(c),c.innerHTML=d,g[d]=c};this.upLabels=function(){for(var b in a.inputs)f[b].firstChild.data=b+":"+(!isFinite(a.inputs[b].src.val)?a.inputs[b].src.val:~~(a.inputs[b].src.val*100)/100);for(b in a.outputs)g[b].firstChild.data=b+":"+(!isFinite(a.outputs[b].val)?a.outputs[b].val:~~(a.outputs[b].val*
100)/100)};this.makeLabels();this.resize=function(){var e=15*(Math.max(objectSize(a.inputs),objectSize(a.outputs))+1)+(this.title?14:0);this.h=e+this.box.clientHeight+(this.box.clientHeight?10:0);this.w=Math.max(120,this.box.clientWidth+20);this.box.style.top=e;b.style.width=this.w;b.style.height=this.h;c.width=this.w;c.height=this.h;d=c.getContext("2d");this.width&&this.redraw()};var h=this,i=function(b){var d=getMouse(b);if(b.target.type!="textarea"&&b.target.type!="range")if(b.altKey)selected.indexOf(a)==
-1&&select(a),duplicate();else{if(b=j(a.inputs,d)){var c=a.inputs[b];if(c.src.node){wiring=[c.src.node,c.srcPort,new Wire(d,c.src.pt),d];rmWire(a,b);return}}else if(b=j(a.outputs,d)){var c=a.outputs[b],e=new Wire(d,c.pt,"#555");wiring=[a,b,e,d];return}if(selected.indexOf(a)==-1){d=selected;selected=[];for(e in d)d[e].widget.redraw();selected.push(a);h.redraw()}dragging=selected}};b.onmousedown=i;b.ontouchmove=function(a){i(a.targetTouches[0])};b.onmouseup=function(b){if(wiring&&(b=getMouse(b),b=j(a.inputs,
b)))a.inputs[b].src.node&&rmWire(a,b),mkWire(wiring[0],wiring[1],a,b,200),wiring[2].remove(),wiring=false};b.onclick=function(b){var b=getMouse(b),d;if(d=j(a.inputs,b))b=a.inputs[d],b.src.node||new EditBox(b.pt,a.inputs[d].src.val,function(b){a.inputs[d].src.val=b;a.inputs[d].src.flag=-1})};var j=function(a,b){for(var d in a){var c=a[d];if(Math.dist(c.pt[0],c.pt[1],b[0],b[1])<=5.5)return d}return false};this.upLoc=function(d,c){this.x=d||this.x;this.y=c||this.y;b.style.top=this.y+"px";b.style.left=
this.x+"px";var i=12,j=15+(this.title?14:0),k;for(k in a.inputs){var l=a.inputs[k];if(!l.pt)l.pt=[];l.pt[0]=[i+this.x];l.pt[1]=[j+this.y];if(f[k])f[k].style.left=i+"px",f[k].style.top=j+"px";j+=15}i=this.w-i;j=15+(this.title?14:0);for(k in a.outputs){l=a.outputs[k];if(!l.pt)l.pt=[];l.pt[0]=i+this.x;l.pt[1]=j+this.y;if(g[k])g[k].style.right="12px",g[k].style.top=j+"px";j+=15}e||h.redraw();this.redrawWires()};this.redraw=function(){var b=selected.indexOf(a)!=-1;d.clearRect(0,0,this.w,this.h);d.fillStyle=
"hsla(200, 80%, 90%,.8)";d.strokeStyle="hsl(200, 70%, "+(b?35:40)+"%)";d.lineWidth=b?4:2;roundRect(d,3,3,this.w-6,this.h-6,7,true,true);d.lineWidth=2;if(this.title)d.fillStyle="hsla(200, 80%, 97%,.9)",roundRect(d,3,3,this.w-6,14,7,true,false),d.font="11px sans-serif",d.textBaseline="top",d.textAlign="center",d.fillStyle="black",d.fillText(this.title,this.w/2,4);d.font="10px sans-serif";for(var c in a.inputs){var b=a.inputs[c].pt[0]-this.x,f=a.inputs[c].pt[1]-this.y;d.fillStyle=h.inWires[c]?h.inWires[c].color:
"hsl(200, 80%, 95%)";circle(d,b,f,3.5)}for(c in a.outputs)b=a.outputs[c].pt[0]-this.x,f=a.outputs[c].pt[1]-this.y,d.fillStyle=h.outWires[c]&&h.outWires[c].length?h.outWires[c][0].color:"hsl(200, 80%, 95%)",circle(d,b,f,3.5);e=true};this.redrawWires=function(){for(var a in h.inWires)h.inWires[a].redraw();for(a in h.outWires)for(var b in h.outWires[a])h.outWires[a][b].redraw()};this.remove=function(){canvDiv.removeChild(b)}};
function EditBox(a,b,c){var d=document.createElement("div");d.className="editBox";var e=document.createElement("input");d.appendChild(e);d.style.left=a[0]+"px";d.style.top=a[1]+"px";d.style.width="50px";e.style.width="100%";canvDiv.appendChild(d);ths=this;e.value=b;e.select();e.focus();e.onchange=function(){ths.remove();c(e.value)};this.remove=function(){if(canvDiv.contains(d))try{canvDiv.removeChild(d)}catch(a){}};e.onblur=function(){ths.remove()}}
function circle(a,b,c,d){a.beginPath();a.arc(b,c,d,0,Math.PI*2,false);a.stroke();a.fill()}function roundRect(a,b,c,d,e,f,g,h){typeof h=="undefined"&&(h=true);typeof f==="undefined"&&(f=5);a.beginPath();a.moveTo(b+f,c);a.lineTo(b+d-f,c);a.quadraticCurveTo(b+d,c,b+d,c+f);a.lineTo(b+d,c+e-f);a.quadraticCurveTo(b+d,c+e,b+d-f,c+e);a.lineTo(b+f,c+e);a.quadraticCurveTo(b,c+e,b,c+e-f);a.lineTo(b,c+f);a.quadraticCurveTo(b,c,b+f,c);a.closePath();h&&a.stroke();g&&a.fill()};var types=[{type:"X2",title:"*2",i:{a:0},o:{b:0},f:function(a,b){b.b=a.a*2}},{type:"Logger",title:"console.log()",i:{msg:""},f:function(a){console.log(a.msg)}},{type:"Summer",title:"Sum",i:{a:1,b:2},o:{c:3},f:function(a,b){b.c=1*a.a+1*a.b}},{type:"Sine",title:"Sine",i:{freq:2,amp:1,phase:0},o:{y:0},step:function(a,b){b.y=Math.sin(curTime*Math.PI*2*parseFloat(a.freq)+parseFloat(a.phase))*a.amp}},{type:"Time",title:"Time",o:{t:0},step:function(a,b){b.t=curTime}},{type:"Mouse",title:"Mouse",o:{x:0,y:0},
init:function(a,b,c){c.handleMove=function(a){a=getMouse(a);c.widget.upLabels();b.x=a[0];b.y=a[1]};document.addEventListener("mousemove",c.handleMove,false)},remove:function(){}},{type:"Scope",i:{x:0,y1:0,y2:0,y3:0},init:function(a,b,c){c._={};var d=c._,e=c.widget.box,d=c._;d.w=300;d.h=150;e.style.width=d.w+"px";e.style.height=d.h+"px";e.style.backgroundColor="rgb(255,255,251)";e.style.minWidth="20px";d.canv=document.createElement("canvas");d.ctx=d.canv.getContext("2d");e.appendChild(d.canv);e.style.resize=
"both";e.style.overflow="hidden";d.canv.style["pointer-events"]="none";d.newDat=false;var f=0,g=0;e.onmousemove=function(){if(e.clientWidth!=f||e.clientHeight!=g)f=e.clientWidth,g=e.clientHeight,c.widget.resize(),c.widget.upLoc(),c.widget.redraw(),f=e.clientWidth,g=e.clientHeight,d.w=f,d.h=g,d.canv.width=d.w,d.canv.height=d.h};d.buffer=[];d.dMin=1E5;d.dMax=-1E5;d.colors=["#00A","#A00","#0A0"];e.ondblclick=function(){d.buffer=[];d.dMin=1E5;d.dMax=-1E5;c.eval()};c.widget.resize()},f:function(a,b,c){var b=
c._,c=[],d;for(d in a)if(c.push(a[d]),d!="x")b.dMax=Math.max(a[d],b.dMax),b.dMin=Math.min(a[d],b.dMin);b.buffer.push(c)},draw:function(a,b,c){b=c._;c=b.ctx;c.clearRect(0,0,b.w,b.h);var d=1,e;for(e in a){c.beginPath();for(var f=0,g=Math.max(b.buffer.length-sps*20+1,0);g<b.buffer.length;g++){var h=b.buffer[g][0]*b.w/2%b.w,i=(1-(b.buffer[g][d]-b.dMin)/(b.dMax-b.dMin))*b.h;h<f?c.moveTo(h,i):c.lineTo(h,i);f=h}c.strokeStyle=b.colors[(d-1)%b.colors.length];c.lineWidth=".6";c.stroke();d++}}},{type:"Custom",
title:"custom",i:{a:1},o:{x:0,y:0,z:0},vars:{txt:"o.x=Math.sin(3.1*Math.PI*i.a)\n\t+Math.sin(7*Math.PI*i.a)/2-3;\n\no.y=Math.random()-6;\no.z=i.a % 1;"},init:function(a,b,c){a=c.widget.box;c._={};b=c._;b.w=200;b.h=80;var d=document.createElement("textarea");d.style.width=b.w+"px";d.style.height=b.h+"px";a.style["pointer-events"]="auto";a.appendChild(d);c.widget.resize();d.onchange=function(){c.vars.txt=d.value;c.newCode(c.vars.txt)};d.value=c.vars.txt;d.onchange();var e=0,f=0;d.onmousemove=function(){if(d.clientWidth!=
e||d.clientHeight!=f)e=d.clientWidth,f=d.clientHeight,c.widget.resize(),c.widget.upLoc(),c.widget.redraw(),e=d.clientWidth,f=d.clientHeight}}},{type:"hSlider",o:{o:0},vars:{value:0},init:function(a,b,c){var d=document.createElement("input");d.type="range";d.min=-1;d.max=1;d.step=0.0010;c.widget.box.appendChild(d);c.widget.resize();d.value=c.vars.value;d.onchange=function(){c.vars.value=d.value;b.o=d.value;c.widget.upLabels()}}},{type:"Accel",title:"Accelerometer",o:{x:0,y:0},init:function(a,b,c){c.tilt=
function(a){b.x=a[0];b.y=a[1]};window.DeviceOrientationEvent?window.addEventListener("deviceorientation",function(){c.tilt([event.beta,event.gamma])},true):window.DeviceMotionEvent?window.addEventListener("devicemotion",function(){c.tilt([event.acceleration.x*2,event.acceleration.y*2])},true):window.addEventListener("MozOrientation",function(){c.tilt([orientation.x*50,orientation.y*50])},true)}},{type:"check",title:"",o:{o:false},vars:{checked:false},init:function(a,b,c){var d=document.createElement("input");
d.type="checkbox";c.widget.box.appendChild(d);c.widget.resize();d.checked=c.vars.checked;d.onchange=function(){c.vars.checked=d.checked;b.o=d.checked;c.widget.upLabels()}}},{type:"button",title:"",o:{o:false},init:function(a,b,c){a=document.createElement("input");a.type="button";a.value="press";c.widget.box.appendChild(a);c.widget.resize();a.onmousedown=function(){b.o=true;c.widget.upLabels()};a.onmouseup=function(){b.o=false;c.widget.upLabels()}}},{type:"AND",title:"AND",i:{a:0,b:0},o:{y:0},f:function(a,
b){b.y=a.a&&a.b}},{type:"OR",title:"OR",i:{a:0,b:0},o:{y:0},f:function(a,b){b.y=a.a||a.b}},{type:"NAND",title:"NAND",i:{a:0,b:0},o:{y:0},f:function(a,b){b.y=!(a.a&&a.b)}},{type:"NOR",title:"NOR",i:{a:0,b:0},o:{y:0},f:function(a,b){b.y=!(a.a||a.b)}},{type:"NOT",title:"NOT",i:{a:0},o:{y:0},f:function(a,b){b.y=!a.a}},{type:"XOR",title:"XOR",i:{a:0,b:0},o:{y:0},f:function(a,b){b.y=a.a<=0!=a.b<=0}}],nodeTypes={};function makeTypes(){for(var a in types)nodeType(types[a])}
function nodeType(a){nodeTypes[a.type]=function(b){this.inherit=Node;this.inherit(a,b)}};var Wire=function(a,b,c){var d=document.createElement("canvas");canvDiv.appendChild(d);var e;d.style["pointer-events"]="none";d.style.zIndex="-1";this.p1=a;this.p2=b;this.color=c;this.redraw=function(){var f=Math.min(a[0],b[0])-4,g=Math.min(a[1],b[1])-4,h=Math.abs(a[0]-b[0])+8,i=Math.abs(a[1]-b[1])+8;d.style.top=g;d.style.left=f;d.width=h;d.height=i;h=h/3*(a[1]>b[1]?1:2);e=d.getContext("2d");e.strokeStyle=c;e.lineCap="round";e.lineWidth=3.3;e.beginPath();e.moveTo(a[0]-f,a[1]-g);e.bezierCurveTo(h,
a[1]-g,h,b[1]-g,b[0]-f,b[1]-g);e.stroke()};this.remove=function(){canvDiv.removeChild(d)}};function mkWire(a,b,c,d,e){if(a.outputs[b]&&c.inputs[d])isFinite(e)&&(e="hsl("+e+", 50%, 55%)"),c.inputs[d].src=a.outputs[b],c.inputs[d].srcPort=b,e=new Wire(c.inputs[d].pt,a.outputs[b].pt,e),a.outputs[b].flag=1,c.widget.inWires[d]=e,a.widget.outWires[b]||(a.widget.outWires[b]=[]),a.widget.outWires[b].push(e),a.widget.redraw(),c.widget.redraw(),e.redraw()}
function rmWire(a,b){if(a.inputs[b]){var c=a.inputs[b].src.node,d=a.inputs[b].srcPort,e=a.widget.inWires[b];delete a.widget.inWires[b];e.remove();for(var f in c.widget.outWires[d])c.widget.outWires[d][f]==e&&c.widget.outWires[d].splice(f,1);a.inputs[b].src={val:a.inputs[b].src.val,flag:-1};c.widget.redraw();a.widget.redraw()}};
