var canvDiv,flow,nodes=[],curTime=0,fps=60,sps=120,t0=0,dragging=null,mouse=[0,0],wiring,play=true;
function init(){canvDiv=document.getElementById("container");makeTypes();t0=Date.now()/1E3;step();window.setInterval(draw,1E3/fps);importNodes({nodes:[{type:"Logger",x:500,y:200},{type:"Summer",x:200,y:100},{type:"Mouse",x:100,y:180},{type:"Time",x:50,y:410},{type:"Sine",x:50,y:300,i:{freq:0.5}},{type:"Sine",x:200,y:300,i:{freq:4.05}},{type:"Scope",x:500,y:350},{type:"Custom",x:200,y:400},{type:"X2",x:350,y:150}],wires:[{n1:4,p1:"y",n2:5,p2:"amp",color:100},{n1:5,p1:"y",n2:6,p2:"y1",color:220},{n1:1,
p1:"c",n2:8,p2:"a",color:0},{n1:8,p1:"b",n2:0,p2:"msg",color:100},{n1:3,p1:"t",n2:7,p2:"a",color:320},{n1:3,p1:"t",n2:6,p2:"x",color:320},{n1:7,p1:"x",n2:6,p2:"y2",color:0},{n1:7,p1:"y",n2:6,p2:"y3",color:100}]});makeLibrary()}var draw=function(){if(play)for(var a in nodes)nodes[a].draw()},step=function step(){if(play){curTime+=1/sps;for(var b in nodes)nodes[b].eval();for(b in nodes)nodes[b].progress()}window.setTimeout(step,1E3/sps)};
Math.dist=function(a,b,d,c){return Math.sqrt((a-d)*(a-d)+(b-c)*(b-c))};objectSize=function(a){var b=0,d;for(d in a)a.hasOwnProperty(d)&&b++;return b};var Node=function(a,b){this.inputs={};this.outputs={};var d={},c={};this.type=a.type;for(var e in a.i)d[e]=a.i[e];for(e in a.o)c[e]=a.o[e];for(e in b.i)d[e]=b.i[e];for(e in b.o)c[e]=b.o[e];var f=a.init||null,g=a.step||null,h=a.f||function(){};for(e in d)this.inputs[e]={src:{val:d[e],flag:-1}};for(e in c)this.outputs[e]={node:this,val:c[e],flag:false};this.newCode=function(a){h=new Function("i","o","that",a)};e=new Widget(this);e.title=b.title||a.title||"";e.resize();b.x&&b.y&&e.upLoc(b.x,b.y);this.widget=
e;var i=true;f&&f(d,c,this);this.doExport=function(){var a={};a.type=this.type;a.title=this.widget.title;a.x=this.widget.x;a.y=this.widget.y;a.i={};for(var b in this.inputs)a.i[b]=this.inputs[b].src.val;return a};this.draw=function(){i&&(a.draw&&a.draw(d,c,this),this.widget.upLabels(),i=false)};this.eval=function(){var a=false,b;for(b in d)if(this.inputs[b].src.flag){a=true;d[b]=this.inputs[b].src.val;if(this.inputs[b].src.flag==-1)this.inputs[b].src.flag=false;i=true}a&&h(d,c,this);g&&(g(d,c,this),
i=true)};this.progress=function(){for(var a in c)if(this.outputs[a].flag=false,c[a]!=this.outputs[a].val)this.outputs[a].val=c[a],i=this.outputs[a].flag=true};this.remove=function(){a.remove&&a.remove(d,c,this);for(var b in this.widget.inWires)rmWire(this,b);for(var e in nodes){b=nodes[e];for(var f in b.inputs)b.inputs[f].src.node&&b.inputs[f].src.node==this&&rmWire(b,f)}nodes.splice(nodes.indexOf(this),1);this.widget.remove()};this.widget.upLoc();nodes.push(this)};var selectStart,selectBox,selected=[];function makeLibrary(){var a="Add:<ul>",b;for(b in nodeTypes)a+='<li><a href="javascript:new nodeTypes.'+b+'({})">'+b+"</a></li>";a+="</ul>";document.getElementById("library").innerHTML=a}function togglePlay(){play=!play;document.getElementById("playPause").innerHTML=play?"pause":"play"}function saveLocal(){localStorage.setItem("scene",JSON.stringify(exportNodes(nodes)))}
function openLocal(){deleteNodes(nodes);importNodes(JSON.parse(localStorage.getItem("scene")));curTime=0}document.onkeydown=function(a){if(a.target.type!="textarea"&&a.target.type!="text")switch(a.which){case 8:a.preventDefault();deleteNodes(selected);break;case 32:a.preventDefault();togglePlay();break;case 68:duplicate();break;case 67:copyNodes(selected);break;case 86:pasteNodes();break;case 88:cutNodes(selected);break;case 79:openLocal();break;case 83:saveLocal()}};
document.onmousedown=function(a){mouse=getMouse(a);if(a.target.id=="container"||a.target.nodeName=="HTML"){if(!selectBox)selectBox=document.createElement("div"),canvDiv.appendChild(selectBox),selectBox.className="selectBox";selectStart=getMouse(a);doSelectBox()}};function select(a){selected.push(a);a.widget.redraw()}function deselect(a){if(a)selected.splice(selected.indexOf(a),1),a.widget.redraw();else for(a=selected.length-1;a>=0;a--)deselect(selected[a])}
document.onmouseup=function(a){mouse=getMouse(a);dragging=null;wiring&&(wiring[2].remove(),wiring=null);if(selectStart)doSelectBox(),selectStart=false,selectBox.style.visibility="hidden"};
document.onmousemove=function(a){newMouse=getMouse(a);if(dragging){var a=newMouse[0]-mouse[0],b=newMouse[1]-mouse[1],d;for(d in dragging)dragging[d].widget.x+=a,dragging[d].widget.y+=b,dragging[d].widget.upLoc()}wiring&&(wiring[3][0]=newMouse[0],wiring[3][1]=newMouse[1],wiring[2].redraw());if(selectStart)selectBox.style.width=Math.abs(newMouse[0]-selectStart[0])+"px",selectBox.style.height=Math.abs(newMouse[1]-selectStart[1])+"px",selectBox.style.left=Math.min(newMouse[0],selectStart[0])+"px",selectBox.style.top=
Math.min(newMouse[1],selectStart[1])+"px",selectBox.style.visibility="visible",doSelectBox();mouse=newMouse};document.onblur=function(){dragging=null;if(selectStart)selectStart=false,selectBox.style.visibility="hidden"};
function doSelectBox(){var a=Math.min(mouse[0],selectStart[0]),b=Math.max(mouse[0],selectStart[0]),d=Math.min(mouse[1],selectStart[1]),c=Math.max(mouse[1],selectStart[1]),e;for(e in nodes){var f=nodes[e],g=f.widget;(g=g.x<b&&g.x+g.w>a&&g.y<c&&g.y+g.h>d)&&selected.indexOf(f)==-1?select(f):!g&&selected.indexOf(f)!=-1&&deselect(f)}}function deleteNodes(a){for(var b=a.length-1;b>=0;b--){var d=a[b];deselect(d);d.remove()}}function cutNodes(a){copyNodes(a);deleteNodes(a)}
function copyNodes(a){var a=exportNodes(a),b;for(b in a.nodes)a.nodes[b].x-=mouse[0],a.nodes[b].y-=mouse[1];localStorage.setItem("pasteboard",JSON.stringify(a))}function pasteNodes(){var a=JSON.parse(localStorage.getItem("pasteboard")),b;for(b in a.nodes)a.nodes[b].x+=mouse[0],a.nodes[b].y+=mouse[1];a=importNodes(a);deselect();for(b in a)select(a[b])}
function exportNodes(a){var b=[],d=[],c;for(c in a){var e=a[c];b.push(e.doExport());for(var f in e.widget.inWires){var g=e.widget.inWires[f],h;for(h in a){var i=a[h],m;for(m in i.widget.outWires)for(var n in i.widget.outWires[m])g==i.widget.outWires[m][n]&&d.push({n1:h,p1:m,n2:c,p2:f,color:g.color})}}}return{nodes:b,wires:d}}function importNodes(a){var b=[],d;for(d in a.nodes)b[d]=makeNode(a.nodes[d]);for(var c in a.wires)d=a.wires[c],mkWire(b[d.n1],d.p1,b[d.n2],d.p2,d.color);return b}
function makeNode(a){return new nodeTypes[a.type](a)}function duplicate(){var a=exportNodes(selected);deselect();for(var b in a.nodes)a.nodes[b].x+=10,a.nodes[b].y+=10;deselect();a=importNodes(a);for(b in a)select(a[b]);dragging=selected}
function getMouse(a){var b=0,d=0;if(!a)a=window.event;if(a.pageX||a.pageY)b=a.pageX,d=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return[b,d]};var Widget=function(a){this.title="";this.x=20;this.y=40;this.w=120;this.h=80;var b=document.createElement("div");canvDiv.appendChild(b);b.className="node";var d=document.createElement("canvas");b.appendChild(d);var c;d.style["pointer-events"]="none";var e=false;this.box=document.createElement("div");b.appendChild(this.box);this.box.className="nodeBox";this.box.style.position="absolute";this.box.style.top="20px";this.box.style.left="10px";this.inWires={};this.outWires={};var f={},g={};this.makeLabels=
function(){for(var c in a.inputs){var d=document.createElement("div");d.className="iLabel";b.appendChild(d);d.innerHTML=c;f[c]=d}for(c in a.outputs)d=document.createElement("div"),d.className="oLabel",b.appendChild(d),d.innerHTML=c,g[c]=d};this.upLabels=function(){for(var b in a.inputs)f[b].firstChild.data=b+":"+(!isFinite(a.inputs[b].src.val)?a.inputs[b].src.val:~~(a.inputs[b].src.val*100)/100);for(b in a.outputs)g[b].firstChild.data=b+":"+(!isFinite(a.outputs[b].val)?a.outputs[b].val:~~(a.outputs[b].val*
100)/100)};this.makeLabels();this.resize=function(){var e=15*(Math.max(objectSize(a.inputs),objectSize(a.outputs))+1)+(this.title?14:0);this.h=e+this.box.clientHeight+(this.box.clientHeight?10:0);this.w=Math.max(120,this.box.clientWidth+20);this.box.style.top=e;b.style.width=this.w;b.style.height=this.h;d.width=this.w;d.height=this.h;c=d.getContext("2d");this.width&&this.redraw()};var h=this;b.onmousedown=function(b){var c=getMouse(b);if(b.target.type!="textarea"&&b.target.type!="range"){if(b=i(a.inputs,
c)){var d=a.inputs[b];if(d.src.node){wiring=[d.src.node,d.srcPort,new Wire(c,d.src.pt),c];rmWire(a,b);return}}else if(b=i(a.outputs,c)){var d=a.outputs[b],e=new Wire(c,d.pt,"#555");wiring=[a,b,e,c];return}if(selected.indexOf(a)==-1){c=selected;selected=[];for(e in c)c[e].widget.redraw();selected.push(a);h.redraw()}dragging=selected}};b.onmouseup=function(b){if(wiring&&(b=getMouse(b),b=i(a.inputs,b)))a.inputs[b].src.node&&rmWire(a,b),mkWire(wiring[0],wiring[1],a,b,200),wiring[2].remove(),wiring=false};
b.onclick=function(b){var b=getMouse(b),c;if(c=i(a.inputs,b))b=a.inputs[c],b.src.node||new EditBox(b.pt,a.inputs[c].src.val,function(b){a.inputs[c].src.val=b;a.inputs[c].src.flag=-1})};var i=function(a,b){for(var c in a){var d=a[c];if(Math.dist(d.pt[0],d.pt[1],b[0],b[1])<=5.5)return c}return false};this.upLoc=function(c,d){this.x=c||this.x;this.y=d||this.y;b.style.top=this.y+"px";b.style.left=this.x+"px";var i=12,l=15+(this.title?14:0),j;for(j in a.inputs){var k=a.inputs[j];if(!k.pt)k.pt=[];k.pt[0]=
[i+this.x];k.pt[1]=[l+this.y];if(f[j])f[j].style.left=i+"px",f[j].style.top=l+"px";l+=15}i=this.w-i;l=15+(this.title?14:0);for(j in a.outputs){k=a.outputs[j];if(!k.pt)k.pt=[];k.pt[0]=i+this.x;k.pt[1]=l+this.y;if(g[j])g[j].style.right="12px",g[j].style.top=l+"px";l+=15}e||h.redraw();this.redrawWires()};this.redraw=function(){var b=selected.indexOf(a)!=-1;c.clearRect(0,0,this.w,this.h);c.fillStyle="hsla(200, 80%, 90%,.8)";c.strokeStyle="hsl(200, 70%, "+(b?35:40)+"%)";c.lineWidth=b?4:2;roundRect(c,3,
3,this.w-6,this.h-6,7,true,true);c.lineWidth=2;if(this.title)c.fillStyle="hsla(200, 80%, 97%,.9)",roundRect(c,3,3,this.w-6,14,7,true,false),c.font="11px sans-serif",c.textBaseline="top",c.textAlign="center",c.fillStyle="black",c.fillText(this.title,this.w/2,4);c.font="10px sans-serif";for(var d in a.inputs){var b=a.inputs[d].pt[0]-this.x,f=a.inputs[d].pt[1]-this.y;c.fillStyle=h.inWires[d]?h.inWires[d].color:"hsl(200, 80%, 95%)";circle(c,b,f,3.5)}for(d in a.outputs)b=a.outputs[d].pt[0]-this.x,f=a.outputs[d].pt[1]-
this.y,c.fillStyle=h.outWires[d]&&h.outWires[d].length?h.outWires[d][0].color:"hsl(200, 80%, 95%)",circle(c,b,f,3.5);e=true};this.redrawWires=function(){for(var a in h.inWires)h.inWires[a].redraw();for(a in h.outWires)for(var b in h.outWires[a])h.outWires[a][b].redraw()};this.remove=function(){canvDiv.removeChild(b)}};
function EditBox(a,b,d){var c=document.createElement("div");c.className="editBox";var e=document.createElement("input");c.appendChild(e);c.style.left=a[0]+"px";c.style.top=a[1]+"px";c.style.width="50px";e.style.width="100%";canvDiv.appendChild(c);ths=this;e.value=b;e.select();e.focus();e.onchange=function(){ths.remove();d(e.value)};this.remove=function(){if(canvDiv.contains(c))try{canvDiv.removeChild(c)}catch(a){}};e.onblur=function(){ths.remove()}}
function circle(a,b,d,c){a.beginPath();a.arc(b,d,c,0,Math.PI*2,false);a.stroke();a.fill()}function roundRect(a,b,d,c,e,f,g,h){typeof h=="undefined"&&(h=true);typeof f==="undefined"&&(f=5);a.beginPath();a.moveTo(b+f,d);a.lineTo(b+c-f,d);a.quadraticCurveTo(b+c,d,b+c,d+f);a.lineTo(b+c,d+e-f);a.quadraticCurveTo(b+c,d+e,b+c-f,d+e);a.lineTo(b+f,d+e);a.quadraticCurveTo(b,d+e,b,d+e-f);a.lineTo(b,d+f);a.quadraticCurveTo(b,d,b+f,d);a.closePath();h&&a.stroke();g&&a.fill()};var types=[{type:"X2",title:"*2",i:{a:0},o:{b:0},f:function(a,b){b.b=a.a*2}},{type:"Logger",title:"console.log()",i:{msg:""},f:function(a){console.log(a.msg)}},{type:"Summer",title:"Sum",i:{a:1,b:2},o:{c:3},f:function(a,b){b.c=parseFloat(a.a)+parseFloat(a.b)}},{type:"Sine",title:"Sine",i:{freq:2,amp:1,phase:0},o:{y:0},step:function(a,b){b.y=Math.sin(curTime*Math.PI*2*parseFloat(a.freq)+parseFloat(a.phase))*a.amp}},{type:"Time",title:"Time",o:{t:0},step:function(a,b){b.t=curTime}},{type:"Mouse",title:"Mouse",
o:{x:0,y:0},init:function(a,b,d){d.handleMove=function(a){a=getMouse(a);d.widget.upLabels();b.x=a[0];b.y=a[1]};document.addEventListener("mousemove",d.handleMove,false)},remove:function(){}},{type:"Scope",i:{x:0,y1:0,y2:0,y3:0},init:function(a,b,d){d._={};var c=d._,e=d.widget.box,c=d._;c.w=300;c.h=150;e.style.width=c.w+"px";e.style.height=c.h+"px";e.style.backgroundColor="rgb(255,255,251)";e.style.minWidth="20px";c.canv=document.createElement("canvas");c.ctx=c.canv.getContext("2d");e.appendChild(c.canv);
e.style.resize="both";e.style.overflow="hidden";c.canv.style["pointer-events"]="none";c.newDat=false;var f=0,g=0;e.onmousemove=function(){if(e.clientWidth!=f||e.clientHeight!=g)f=e.clientWidth,g=e.clientHeight,d.widget.resize(),d.widget.upLoc(),d.widget.redraw(),f=e.clientWidth,g=e.clientHeight,c.w=f,c.h=g,c.canv.width=c.w,c.canv.height=c.h};c.buffer=[];c.dMin=1E5;c.dMax=-1E5;c.colors=["#00A","#A00","#0A0"];e.ondblclick=function(){c.buffer=[];c.dMin=1E5;c.dMax=-1E5;d.eval()};d.widget.resize()},f:function(a,
b,d){var b=d._,d=[],c;for(c in a)if(d.push(a[c]),c!="x")b.dMax=Math.max(a[c],b.dMax),b.dMin=Math.min(a[c],b.dMin);b.buffer.push(d)},draw:function(a,b,d){b=d._;d=b.ctx;d.clearRect(0,0,b.w,b.h);var c=1,e;for(e in a){d.beginPath();for(var f=0,g=Math.max(b.buffer.length-sps*20+1,0);g<b.buffer.length;g++){var h=b.buffer[g][0]*b.w/2%b.w,i=(1-(b.buffer[g][c]-b.dMin)/(b.dMax-b.dMin))*b.h;h<f?d.moveTo(h,i):d.lineTo(h,i);f=h}d.strokeStyle=b.colors[(c-1)%b.colors.length];d.lineWidth=".6";d.stroke();c++}}},{type:"Custom",
title:"custom",i:{a:1},o:{x:0,y:0,z:0},init:function(a,b,d){a=d.widget.box;d._={};b=d._;b.w=200;b.h=80;var c=document.createElement("textarea");c.style.width=b.w+"px";c.style.height=b.h+"px";a.style["pointer-events"]="auto";a.appendChild(c);d.widget.resize();c.onchange=function(){d.newCode(c.value)};c.value="o.x=Math.sin(3.1*Math.PI*i.a)\n\t+Math.sin(7*Math.PI*i.a)/2-3;\n\no.y=Math.random()-6;\no.z=i.a % 1;";c.onchange();var e=0,f=0;c.onmousemove=function(){if(c.clientWidth!=e||c.clientHeight!=f)e=
c.clientWidth,f=c.clientHeight,d.widget.resize(),d.widget.upLoc(),d.widget.redraw(),e=c.clientWidth,f=c.clientHeight}}},{type:"hSlider",o:{o:0},init:function(a,b,d){var c=document.createElement("input");c.type="range";c.min=-1;c.max=1;c.step=0.0010;d.widget.box.appendChild(c);d.widget.resize();c.onchange=function(){b.o=c.value;d.widget.upLabels()}}}],nodeTypes={};function makeTypes(){for(var a in types)nodeType(types[a])}
function nodeType(a){nodeTypes[a.type]=function(b){this.inherit=Node;this.inherit(a,b)}};var Wire=function(a,b,d){var c=document.createElement("canvas");canvDiv.appendChild(c);var e;c.style["pointer-events"]="none";c.style.zIndex="-1";this.p1=a;this.p2=b;this.color=d;this.redraw=function(){var f=Math.min(a[0],b[0])-4,g=Math.min(a[1],b[1])-4,h=Math.abs(a[0]-b[0])+8,i=Math.abs(a[1]-b[1])+8;c.style.top=g;c.style.left=f;c.width=h;c.height=i;h=h/3*(a[1]>b[1]?1:2);e=c.getContext("2d");e.strokeStyle=d;e.lineCap="round";e.lineWidth=3.3;e.beginPath();e.moveTo(a[0]-f,a[1]-g);e.bezierCurveTo(h,
a[1]-g,h,b[1]-g,b[0]-f,b[1]-g);e.stroke()};this.remove=function(){canvDiv.removeChild(c)}};function mkWire(a,b,d,c,e){if(a.outputs[b]&&d.inputs[c])isFinite(e)&&(e="hsl("+e+", 50%, 55%)"),d.inputs[c].src=a.outputs[b],d.inputs[c].srcPort=b,e=new Wire(d.inputs[c].pt,a.outputs[b].pt,e),a.outputs[b].flag=1,d.widget.inWires[c]=e,a.widget.outWires[b]||(a.widget.outWires[b]=[]),a.widget.outWires[b].push(e),a.widget.redraw(),d.widget.redraw(),e.redraw()}
function rmWire(a,b){if(a.inputs[b]){var d=a.inputs[b].src.node,c=a.inputs[b].srcPort,e=a.widget.inWires[b];delete a.widget.inWires[b];e.remove();for(var f in d.widget.outWires[c])d.widget.outWires[c][f]==e&&d.widget.outWires[c].splice(f,1);a.inputs[b].src={val:a.inputs[b].src.val,flag:-1};d.widget.redraw();a.widget.redraw()}};
